In [1]:
import tensorflow as tf

In [2]:
kernel = tf.constant([
    [
        [[-1.,0.,0.],[0.,-1.,0.],[0.,0.,-1]],
        [[-1.,0.,0.],[0.,-1.,0.],[0.,0.,-1.]],
        [[-1.,0.,0.],[0.,-1.,0.],[0.,0.,-1.]],
    ],
    [
        [[-1.,0.,0.],[0.,-1.,0.],[0.,0.,-1]],
        [[8.,0.,0.],[0.,8.,0.],[0.,0.,8.]],
        [[-1.,0.,0.],[0.,-1.,0.],[0.,0.,-1.]],
    ],
    [
        [[-1.,0.,0.],[0.,-1.,0.],[0.,0.,-1]],
        [[-1.,0.,0.],[0.,-1.,0.],[0.,0.,-1.]],
        [[-1.,0.,0.],[0.,-1.,0.],[0.,0.,-1.]],
    ]
])

In [3]:
image_filename = "./MyDog.jpg"
filename_queue = tf.train.string_input_producer(tf.train.match_filenames_once(image_filename))

image_reader = tf.WholeFileReader()
_,image_file = image_reader.read(filename_queue)
image = tf.image.decode_jpeg(image_file)
image = tf.cast(image, tf.float32)

In [10]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(sess=sess,coord=coord)
    
    conv2d = tf.nn.conv2d([image],kernel,strides=[1,1,1,1],padding="SAME")
    activation_map = sess.run(tf.minimum(tf.nn.relu(conv2d),255))
    
    print(activation_map)
    coord.request_stop()
    coord.join(threads)
    sess.close()

[[[[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 243.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [ 60.  51.  54.]
   [ 67.  58.  61.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [  4.   4.   4.]
   [  0.   0.   0.]
   ...
   [ 26.  29.  19.]
   [ 21.  27.  16.]
   [255. 255. 255.]]

  ...

  [[255. 255. 255.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [  2.   5.   0.]
   [  4.   7.   0.]
   [255. 255. 103.]]

  [[255. 255. 255.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [251. 255.  83.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [208. 255.  44.]
   [194. 248.  26.]
   [255. 255.  92.]]]]
